config/routes.rb
Rails.application.routes.draw do
  resources :jeeps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jeep.rb
class Jeep < ApplicationRecord

  def self.create_bulk_jeeps(jeep_collection)
    jeep_collection.each do |jeep|
      Jeep.create(jeep)
    end
  end

  def price_after_tax
    sales_tax = 0.089
    price + (price * sales_tax)
  end

end

# == Schema Information
#
# Table name: jeeps
#
#  id             :integer          not null, primary key
#  bids           :integer
#  miles          :integer
#  name           :string
#  price          :float
#  time_remaining :string
#  year           :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jeeps_controller.rb
class JeepsController < ApplicationController
  before_action :set_jeep, only: %i[ show destroy ]

# GET /jeeps or /jeeps.json
def index
  @jeeps = Jeep.all
end

# GET /jeeps/1 or /jeeps/1.json
def show
end

# DELETE /jeeps/1 or /jeeps/1.json
def destroy
  @jeep.destroy
  respond_to do |format|
    format.html { redirect_to jeeps_url, notice: "jeep was successfully destroyed." }
    format.json { head :no_content }
  end
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_jeep
    @jeep = Jeep.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def jeep_params
    params.require(:jeep).permit(:abbreviation, :city, :conference, :division, :full_name, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jeep_helper.rb
module JeepHelper
end

app/views/jeeps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>jeeps</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Time Remaining</th>
      <th>Name</th>
      <th>Bids</th>
      <th>Miles</th>
      <th>Price</th>
      <th>Price After Tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jeeps.each do |jeep| %>
      <tr>
        <td><%= jeep.year %></td>
        <td><%= jeep.time_remaining %></td>
        <td><%= jeep.name %></td>
        <td><%= jeep.bids %></td>
        <td><%= jeep.miles %></td>
        <td><%= number_to_currency(jeep.price) %></td>
        <td><%= number_to_currency(jeep.price_after_tax) %></td>
        <td><%= link_to 'Show', jeep %></td>
        <td><%= link_to 'Destroy', jeep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New jeep', new_jeep_path %>

app/views/jeeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time Remaining:</strong>
  <%= @jeep.time_remaining %>
</p>

<p>
  <strong>Name :</strong>
  <%= @jeep.name %>
</p>

<p>
  <strong>Bids:</strong>
  <%= @jeep.bids %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @jeep.miles %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@jeep.price) %>
</p>

<p>
  <strong>Price After Tax:</strong>
  <%= number_to_currency(@jeep.price_after_tax) %>
</p>

<p>
  <strong>Year:</strong>
  <%= @jeep.year %>
</p>

<%= link_to 'Back', jeeps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>